### ISSUE TITLE
При воспроизведении тестов не находит элемент Input__sub

### ISSUE THREAD

**Issue by evgsemenov** [evgsemenov/5.2.2-Selenide#1]
**Шаги воспроизведения:**
1. Скачать репо
2. Открыть в IDEA 
3. Ввести в консоль команду java -jar artifacts/app-card-delivery.jar
4. Запустить shouldRequireValidTelephoneNumberIfTenNumbersTest() в классе CreditCardDeliveryFormUITest.

**Ожидаемый результат:**
Тест проходит.

**Фактический результат:**
Тест падает с ошибкой 
> NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"[input__sub]"}

![Screenshot_2](https://user-images.githubusercontent.com/39197351/126970051-d3cf2371-e9c7-4891-bbd2-4b24505a4a71.png)

**Comment by andrew-pahomov** [comment]
Добрый день. Проверка видимости сообщения об ошибке и его текста может выглядеть так
```
        $("[data-test-id='phone'].input_invalid .input__sub").shouldBe(visible)
                .shouldHave(exactText("Телефон указан неверно. Должно быть 11 цифр, например, +79012345678."));
```

**Comment by evgsemenov** [comment]
> 
> 
> Добрый день. Проверка видимости сообщения об ошибке и его текста может выглядеть так
> 
> ```
>         $("[data-test-id='phone'].input_invalid .input__sub").shouldBe(visible)
>                 .shouldHave(exactText("Телефон указан неверно. Должно быть 11 цифр, например, +79012345678."));
> ```

Спасибо!
